swagger: "2.0"
info:
  version: 1.0.0
  title: myapp
  description: My cool TypeScript app
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  ExampleBody:
    type: object
    title: test
    required:
      - name
    properties:
      name:
        type: string
      another_one:
        type: string
  anotherBody:
    type: object
    title: resource2
    required:
      - name
    properties:
      name:
        type: string
      value:
        type: boolean

paths:
  /testing:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Examples
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: an example
          required: true
          schema: 
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all examples
  
  /resource2:
     get:
      tags:
        - Examples
      description: Fetch all resource 2s
      responses:
        200:
          description: Returns all resources 2s
     post:
      tags:
        - Examples
      description: Create a new resource2
      parameters:
        - name: example
          in: body
          description: an example
          required: true
          schema: 
            $ref: "#/definitions/anotherBody"
      responses:
        200:
          description: Returns all examples

  /testing/{id}:
     get:
       tags:
       - Examples
     parameters:
       - name: id
         in: path
         required: true
         description: The id of the example to retrieve
         type: integer
     responses:
       200:
         description: Return the example with the specified id
       404:
         description: Example not found
  
  /token: 
    get:
      tags:
        - Examples
      description: Fetch Users
      responses:
        200:
          description: Returns users from Azure AD
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification